### List all messaggess
GET http://localhost:3000/messages/list

### Create a new message
POST http://localhost:3000/messages/save
content-Type: application/json

{
    "content": "hi there"
}

### Get Particular Message
GET http://localhost:3000/messages/1

